### ISSUE TITLE
SetLang is not thread safe

### ISSUE THREAD

**Issue by Rain-31** [mylukin/easy-i18n#1]
Am i right?

**Comment by Rain-31** [comment]
And in some cases I think it has memory leak

**Comment by mylukin** [comment]
> And in some cases I think it has memory leak

I am not very familiar with thread safety, do you know how to modify it?  I just used golang for a month

**Comment by Rain-31** [comment]
i fix thread safe with a session id, but it change function args

= #2

**Comment by Rain-31** [comment]
and i think my version still has memory leak, i don't konw how golang gc deal with point in map

**Comment by mylukin** [comment]
> and i think my version still has memory leak, i don't konw how golang gc deal with point in map

I think it is only necessary to add a lock to ensure that the variables are correct in each thread. There is no need to care whether there will be a memory overflow. p points to a memory address, and theoretically there will be no memory overflow.

**Comment by mylukin** [comment]
> i fix thread safe with a session id, but it change function args
> #2 

This usage is not elegant

**Comment by Rain-31** [comment]
> > i fix thread safe with a session id, but it change function args
> > #2
> 
> This usage is not elegant

yeah i think it's not good enough too  
than  I  will  keep  those commits in my branch
